sudo: false
language: python
dist: trusty

matrix:
  include:
    - dist: trusty
      sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD="cp27-manylinux1_x86_64 cp36-manylinux1_x86_64 cp37-manylinux1_x86_64"

branches:
  only:
    - master
    - ci

install:
  - pip install cibuildwheel
  - mkdir ../workdir
  - cd ../workdir
  - mv $TRAVIS_BUILD_DIR/py/* .
  - mv $TRAVIS_BUILD_DIR repo

before_script: ls

script:
  - |
    CIBW_ENVIRONMENT="LD_LIBRARY_PATH=\"/host/home/travis/build/b1naryth1ef/telecom/py/:$LD_LIBRARY_PATH\" TELECOM_BUILD_SHARED=1 TELECOM_REPO_PATH=\"./repo/\" PATH=\"$PATH:/usr/local/go/bin\" GOPROXY=\"https://proxy.golang.org\" GO111MODULE=on" \
    CIBW_BEFORE_BUILD="curl https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz -o go.tar.gz && tar -C /usr/local -xzf go.tar.gz && yum install -y gcc" \
    cibuildwheel --output-dir dist .

before_deploy: ls dist/

deploy:
  provider: pypi
  username: b1naryth1ef
  password:
    secure: SAgTYEAbEVnaFmu5BtXXcA9RPv/UektCYfyrwoQdjYomHZFUvvb4fI6hjKf3sx5gR1bZLNQoPTRsPZpff4CICrYaUNopfAsY371oVWftH/tYxy5TyLywN/6rzLsyAZCADyOBm+IeTcbisxQZMq8mRdVHZZReV6rr9cjoZezuFS3IfWzUqXFzWDdPgxwTBKqcJ3Icc5ofa54igYAkWyGX9jAjCm0UVup74+4rmlgcFBEae+2FkEdsi9qbTH6DTHWQeOTU+YF+4md6rABUCud6sW2Ee/j/0H0fmpq7PhKWURN+rpGybm5n91B8nIH8s9kt6aRLaw4rzM8moWgmxooZZ+0wxz+AbxmupG5QappY2nS5CNwEAekLrOM80W4yGk3rQJQESv+iK2MzAfLhNu7D5N7GXSJiejo9XbUSxs2c09328uNXENdGFsGfSRVVW+MFBlzzIzvxmQb+EtJEyra2/wyslAgu3EjZBTe4o3V5qOkLozuyMNuZq/Pv48KAuhQghPs0aLOziKKscl3mfQ5qOfI7I4fnrl2mckRs4sDlVrY6JyfHc/AUw5dTkJy1gMTz+Ok4qP9o35sisf769aQa5kiX1wTdd5n5ofp3skauTlcnAyHRUDAVEqemQOT9GkupLIVtc3Uz2H5IMUxmynhRxLPtKcsr5jHEhf3b4o4VZlo=
  on:
    tags: true
    repo: b1naryth1ef/telecom
